version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    environment:
      - APP_ENV=development
      - DB_HOST=db
      - DB_USER=probenplaner
      - DB_PASSWORD=kDo1#a43
      - DB_NAME=probenplaner
    networks:
      - app_net

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=probenplaner
      - MYSQL_USER=probenplaner
      - MYSQL_PASSWORD=kDo1#a43
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - app_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - db
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  db_data: 